//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutogearWeb.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.Bookings = new HashSet<Booking>();
            this.Bookings1 = new HashSet<Booking>();
            this.Instructor_Leaves = new HashSet<Instructor_Leaves>();
            this.Instructor_Leaves1 = new HashSet<Instructor_Leaves>();
            this.Instructor_Student = new HashSet<Instructor_Student>();
            this.Instructor_Student1 = new HashSet<Instructor_Student>();
            this.Package_Details = new HashSet<Package_Details>();
            this.Package_Details1 = new HashSet<Package_Details>();
            this.Student_Address = new HashSet<Student_Address>();
            this.Student_Address1 = new HashSet<Student_Address>();
            this.Students = new HashSet<Student>();
            this.Students1 = new HashSet<Student>();
            this.Users = new HashSet<User>();
        }
    
        public string Id { get; set; }
        public string Hometown { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Jobtitle { get; set; }
        public string Educationlevel { get; set; }
        public string Country { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Booking> Bookings1 { get; set; }
        public virtual ICollection<Instructor_Leaves> Instructor_Leaves { get; set; }
        public virtual ICollection<Instructor_Leaves> Instructor_Leaves1 { get; set; }
        public virtual ICollection<Instructor_Student> Instructor_Student { get; set; }
        public virtual ICollection<Instructor_Student> Instructor_Student1 { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual ICollection<Package_Details> Package_Details { get; set; }
        public virtual ICollection<Package_Details> Package_Details1 { get; set; }
        public virtual ICollection<Student_Address> Student_Address { get; set; }
        public virtual ICollection<Student_Address> Student_Address1 { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Student> Students1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
