//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutogearWeb.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public Instructor()
        {
            this.Bookings = new HashSet<Booking>();
            this.Instructor_Leaves = new HashSet<Instructor_Leaves>();
            this.Instructor_Student = new HashSet<Instructor_Student>();
        }
    
        public string InstructorId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> Mobile { get; set; }
        public string Email { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Instructor_Leaves> Instructor_Leaves { get; set; }
        public virtual ICollection<Instructor_Student> Instructor_Student { get; set; }
    }
}
