//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutogearWeb.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_License
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string LicenseNo { get; set; }
        public int StateId { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Class { get; set; }
        public Nullable<System.DateTime> License_passed_Date { get; set; }
        public string Remarks { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
