//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutogearWeb.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Bookings = new HashSet<Booking>();
            this.Student_Address = new HashSet<Student_Address>();
        }
    
        public int S_Number { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Student_Address> Student_Address { get; set; }
    }
}
